### PR TITLE
MEN-4258: fix login with password from STDIN

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by tranchitella** [comment]
@lluiscampos how am I supposed to deal with codecov? See the pipeline for the details.

**Comment by tranchitella** [comment]
I manually launched the GitLab CI/CD pipeline setting the codecov token, and it seems to work.

**Review by oleorhagen — APPROVED** [review]
Looks good.

I don't have time to look at codecov right now though

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Missing `Changelog` that we added in #94.

Just ignore the coverage, I am will be reviewing `mender-cli` as part of [QA-105](https://tracker.mender.io/browse/QA-105)

**Comment by tranchitella** [comment]
> Missing `Changelog` that we added in #94.

Done!

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
