### PR TITLE
--token command fixes.

### PR DESCRIPTION
**Pull request by svenschwermer**

### CODE REVIEW

**Review by kjaskiewiczz — COMMENTED** [review]
@svenschwermer thanks for your contribution!
can you update copyright dates in files you have changed?
could you also change commit messages to follow conventional commits (info [here](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#structuring-your-commits))?

**Comment by merlin-northern** [comment]
hello @svenschwermer the code looks good thank you very much for another of your excellent contributions. I created this one: https://github.com/mendersoftware/mender-cli/pull/181 carrying over your commits and adjusting little things. I want to keep you and recognise as the author. could you try to align this PR accordingly?

**Comment by svenschwermer** [comment]
Hey guys, sorry, I hadn't seen your comments until now. I updates the commit according to your feedback, let me know if this state is acceptable.

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please baby

**Comment by merlin-northern** [comment]
> Hey guys, sorry, I hadn't seen your comments until now. I updates the commit according to your feedback, let me know if this state is acceptable.

hey. no worries. thank you for fixing. the only thing I did was to add change logs. I took the liberty to force push to your branch. since you singed off the commits you are recognised as an author and much appreciated as Mender Contributor. it is a pleasure to work with you. as soon as the pipeline has passed, I will merge.

**Review by merlin-northern — APPROVED** [review]

**Pull request merged**
