### PR TITLE
New command artifacts delete

### PR DESCRIPTION
**Pull request by rschwarz-sotec**
Changelog: New command `mender-cli artifacts delete ID` to delete an
artifact

Signed-off-by: Ruben Schwarz <r.schwarz@sotec.eu>

### CODE REVIEW

**Comment by tranchitella** [comment]
Thanks for your contribution, @rschwarz-sotec.
Would it be possible to write unit tests for the new command?

**Comment by rschwarz-sotec** [comment]
Hi @tranchitella 
as far as I saw there are no unit tests, just integration tests for this kind of commands. I am not very familiar how to write those tests, It looks like they are written in python which completely new to me.
I can try to write tests, is there a documentation for it? Or do you have a starting point where I can look to?

**Comment by tranchitella** [comment]
You are right, @rschwarz-sotec. This repositories relies on integration tests, which we write in Python.
My colleague @MaciejTe will take care of that.

**Review by MaciejTe — APPROVED** [review]
Looks good Sir!

**Comment by MaciejTe** [comment]
@rschwarz-sotec PR with tests is here: https://github.com/mendersoftware/mender-cli/pull/148

**Pull request merged**
