### PR TITLE
Store login token in XDG Base Dir Spec Cache-directory

### PR DESCRIPTION
**Pull request by andhe**

### CODE REVIEW

**Comment by andhe** [comment]
Possible TODOs:

* If default token doesn't exist in new path, but in old you might want to move it
* Clean up leftovers in the old path (rmdir ~/.mender/)
* Consider if you need to update anything in vendor/

**Comment by andhe** [comment]
Using the "godata" source for a package which implements the XDG base dir spec might not be the best choice. Unsure exactly what to pick. Since there already seems to exist >10 different implementations all flawed in their own way I probably shouldn't invent another one but it might be wise for mender-cli to just carry its own helper function for now......

**Comment by mirzak** [comment]
@kjaskiewiczz @mchalski

**Comment by merlin-northern** [comment]
as requested by @mirzak merged.

**Pull request merged**
