### PR TITLE
Add public ACL to published object in mender-cli

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Debugging on CI. Do not review yet.

**Comment by lluiscampos** [comment]
Ready for review. Can you double check @merlin-northern?

**Comment by merlin-northern** [comment]
> Ready for review. Can you double check @merlin-northern?

looks good to me!
that was perfect sync!

I would add:
```bash
[[ $(curl -o /dev/null -s -w "%{http_code}" https://${S3_BUCKET_NAME}.s3.amazonaws.com/${S3_BUCKET_PATH}/${CI_COMMIT_REF_NAME}/mender-cli) =~ 2.. ]] || exit 1;
```
or something similar, to be sure the links work.

**Comment by lluiscampos** [comment]
> I would add:
> 
> ```shell
> [[ $(curl -o /dev/null -s -w "%{http_code}" https://${S3_BUCKET_NAME}.s3.amazonaws.com/${S3_BUCKET_PATH}/${CI_COMMIT_REF_NAME}/mender-cli) =~ 2.. ]] || exit 1;
> ```
> 
> or something similar, to be sure the links work.

It doesn't work for me locally:
```
curl https://mender.s3.amazonaws.com/mender-cli/master/mender-cli
curl: (6) Could not resolve host: mender.s3.amazonaws.com
```

And also, I am not confident that checking the link here creates a lot of value. We do have the dead link checker for this which is an independent 3rd party guy.

**Comment by lluiscampos** [comment]
@merlin-northern ^

**Comment by merlin-northern** [comment]
> > I would add:
> > ```shell
> > [[ $(curl -o /dev/null -s -w "%{http_code}" https://${S3_BUCKET_NAME}.s3.amazonaws.com/${S3_BUCKET_PATH}/${CI_COMMIT_REF_NAME}/mender-cli) =~ 2.. ]] || exit 1;
> > ```
> > 
> > 
> > or something similar, to be sure the links work.
> 
> It doesn't work for me locally:
> 
> ```
> curl https://mender.s3.amazonaws.com/mender-cli/master/mender-cli
> curl: (6) Could not resolve host: mender.s3.amazonaws.com
> ```

thats strange, or even really strange. the following is executed from some standalone host far away from our infrastructure knowing nothing about mender:
```bash
#host mender.s3.amazonaws.com
mender.s3.amazonaws.com is an alias for s3-1-w.amazonaws.com.
s3-1-w.amazonaws.com has address 52.216.186.59
#host mender.s3.amazonaws.com 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

mender.s3.amazonaws.com is an alias for s3-1-w.amazonaws.com.
s3-1-w.amazonaws.com has address 52.216.238.75
```

how can it not work for you?
> 
> And also, I am not confident that checking the link here creates a lot of value. We do have the dead link checker for this which is an independent 3rd party guy.

well, I am sure that checking that the link still works after you have uploaded something is a good idea, especially that we messed that, and the links were not working, and no one noticed. I leave it to you to decide.

**Comment by lluiscampos** [comment]
> how can it not work for you?

It works now. It was temporary unavailable for some reason.

> well, I am sure that checking that the link still works after you have uploaded something is a good idea, especially that we messed that, and the links were not working, and no one noticed. I leave it to you to decide.

We noticed it thought the dead link checker. And that is my point: I think it is better to check it from an external party, which will check both the master one (uploaded here), the tagged ones (which are not uploaded here but from mender-qa).

**Pull request merged**
